CREATE DATABASE IF NOT EXISTS hotel_db;
USE hotel_db;

CREATE TABLE CLIENTE (
    id_cliente  INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    telefono VARCHAR(20)
);

CREATE TABLE HABITACION (
    id_habitacion INT AUTO_INCREMENT PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    precio DECIMAL(10,2) NOT NULL
);

CREATE TABLE EMPLEADO (
    id_empleado INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    puesto VARCHAR(50) NOT NULL
);

CREATE TABLE RESERVA (
    id_reserva INT AUTO_INCREMENT PRIMARY KEY,
    fecha_entrada DATE NOT NULL,
    fecha_salida DATE NOT NULL,
    CLIENTE_id_cliente INT NOT NULL,
    HABITACION_id_habitacion INT NOT NULL,
    FOREIGN KEY (CLIENTE_id_cliente) REFERENCES CLIENTE(id_cliente),
    FOREIGN KEY (HABITACION_id_habitacion) REFERENCES HABITACION(id_habitacion)
);

CREATE TABLE PAGO (
    id_pago INT AUTO_INCREMENT PRIMARY KEY,
    fecha_pago DATETIME NOT NULL,
    monto DECIMAL(10,2) NOT NULL,
    metodo_pago VARCHAR(30) NOT NULL,
    RESERVA_id_reserva INT NOT NULL,
    EMPLEADO_id_empleado INT NOT NULL,
    FOREIGN KEY (RESERVA_id_reserva) REFERENCES RESERVA(id_reserva),
    FOREIGN KEY (EMPLEADO_id_empleado) REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE LOG_HABITACION (
    timestamp DATETIME(6) NOT NULL,
    status VARCHAR(30) NOT NULL,
    HABITACION_id_habitacion INT NOT NULL,
    PRIMARY KEY (timestamp, HABITACION_id_habitacion),
    FOREIGN KEY (HABITACION_id_habitacion) REFERENCES HABITACION(id_habitacion)
);
